config/routes.rb
How::Application.routes.draw do
  root to: "topics#index"
  resources :topics do
    resources :steps
  end
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :topic
  attr_accessible :description
  validates :description, presence: true
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :subject
  validates :subject, :presence => true
  has_many :steps, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_filter :find_topic
  before_filter :find_step, only: [:show, :edit, :update, :destroy]


  def new
    @step = @topic.steps.build
  end

  def create
    @step = @topic.steps.build(params[:step])
    if @step.save
      flash[:notice] = "Step has been created."
      redirect_to [@topic, @step]
    else
      flash[:alert] = "Step has not been created."
      render action: "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @step.update_attributes(params[:step])
      flash[:notice] = "Step has been updated."
      redirect_to [@topic, @step]
    else
      flash[:alert] = "Step has not been updated."
      render action: "edit"
    end
  end

  def destroy
    @step.destroy
    flash[:notice] = "Step has been deleted."
    redirect_to @topic
  end
private

  def find_topic
    @topic = Topic.find(params[:topic_id])
  end

  def find_step
    @step = @topic.steps.find(params[:id])
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(params[:topic])
    if @topic.save
      flash[:notice] = "Topic has been created."
      redirect_to @topic
    else
      flash[:alert] = "Topic has not been created."
      render action: "new"
    end
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update_attributes(params[:topic])
      flash[:notice] = "Topic has been updated."
      redirect_to @topic
    else
      flash[:alert] = "Topic has not been updated."
      render action: "edit"
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    flash[:notice] = "Topic has been deleted."
    redirect_to topics_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "How").join(" - ")
      end
    end
  end
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
      <%= yield(:title) %>
    <% else %>
      How
    <% end %>
  </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <div class='flash' id='<%=key %>'>
    <%= value %>
  </div>
<% end %>
<%= yield %>

</body>
</html>

app/views/steps/_form.html.erb
<%= form_for [@topic, @step] do |f| %>
  <%= f.error_messages %>
<p>
  <%= f.label :description %><br>
  <%= f.text_field :description %>
</p>
  <%= f.submit %>
<% end %>

app/views/steps/edit.html.erb
<h2>Editing a step in <%= @topic.subject %></h2>
<%= render "form" %>

app/views/steps/new.html.erb
<h2>New Step</h2>
<%= render "form" %>

app/views/steps/show.html.erb
<div id='step'>
  <h2><%= @step.description %></h2>
  <%= simple_format(@step.description) %>
</div>
<%= link_to "All Topics", topics_path(@topic) %>
<%= link_to "View Topic", topic_path(@topic) %>
<%= link_to "New Step", new_topic_step_path(@topic) %>
<%= link_to "Edit Step", [:edit, @topic, @step] %>
<%= link_to "Delete Step", [@topic, @step], :method => :delete,
       :confirm => "Are you SURE you want to delete this step?" %>

app/views/topics/_form.html.erb
<h2>New Topic</h2>
<%= form_for(@topic) do |f| %>
<%= f.error_messages %>
  <p>
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  <%= f.submit %>
<% end %>

app/views/topics/edit.html.erb
<h2>Edit Your Topic!<h2>
  <%= render "form" %>

app/views/topics/index.html.erb
<h2>Topics</h2>
<ul>
  <% @topics.each do |topic| %>
    <li><%=link_to topic.subject, topic %></li>
  <% end %>
</ul>

<%= link_to "New Topic", new_topic_path %>

app/views/topics/new.html.erb
<%= render "form" %>

app/views/topics/show.html.erb
<%= title(@topic.subject, "Topics") %>

<h2><%= @topic.subject %></h2>

<%= link_to "All Topics", topics_path(@topic) %>
<%= link_to "New Topic", new_topic_path(@topic) %>
<%= link_to "Edit Topic", edit_topic_path(@topic) %>
<%= link_to "Delete Topic", topic_path(@topic),
            method: :delete, confirm: "Are you SURE you want to delete this topic?" %>
<%= link_to "New Step", new_topic_step_path(@topic) %>

<ul id='steps'>
  <% @topic.steps.each do |step| %>
    <li>
      #<%= step.id %> -
      <%= link_to step.description, [@topic, step] %>
    </li>
  <% end %>
</ul>